[project]
name = "project-a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "silksnow", email = "tangcwyx@163.com" }
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.0",
    "pillow>=10.0",
]

[project.scripts]
project-a = "project_a:main"

[tool.uv]
package = false